spring:
  application:
    name: integration_demo

urls:
  account: https://accounts.somecompany.com/accounts/
  tracking: https://tracking.somecompany.com/tracking/order/

logging:
  level:
    root: DEBUG